menu:
- {name: 'about', url: '/about'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/assets/documents/Jack_Hopkins_CV.pdf'}
- {name: 'publications', url: '/publications'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/JackHopkins', prefix: 'fab'}
- {icon: 'graduation-cap', link: 'https://scholar.google.com/citations?user=_k4FEiAAAAAJ', prefix: 'fas'}
- {icon: 'twitter', link: 'https://x.com/JackHopkins', prefix: 'fab'}

contacts:
- {name: 'Jack Hopkins', title: 'Independent AI Safety Researcher', email: 'jack.hopkins@me.com'}

